!TransformerTorchEncoder
with:
  pooling_strategy: 'cls'
  pretrained_model_name_or_path: distilbert-base-cased
  max_length: 96
metas:
  workspace: '/docker-workspace'
requests:
  on:
    ControlRequest:
      - !ControlReqDriver {}
    [SearchRequest, TrainRequest, IndexRequest]:
      - !EncodeDriver
        with:
          traversal_paths: ['c']
          batch_size: $JINA_ENCODER_DRIVER_BATCH_SIZE
