name: Docsbot Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      project:
        description: Pass the project name (JINA | FINETUNER | FASTAPI)
        default: JINA
        required: false
      environment:
        description: Pass the environment (prod | stage)
        default: stage
        required: false
      branch:
        description: Pass the jina-docs-bot branch/tag name
        default: main
        required: false

# At a time only one job is allowed to run for an environment to control the load.
# e.g.- 2 jobs with `prod-jina` & `prod-finetuner` cannot run at the same time. 2nd one waits for the 1st.
concurrency: deployment-${{ github.event.inputs.environment }}

jobs:
  reindex-and-redeploy-query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-docs-bot
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Prepare client for deployment
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r deployment/requirements.txt
      - name: Start index Flow, reindex & redeploy query Flow
        run: |
          if [[ ${{ github.event.inputs.environment }} == 'prod' ]] ; then 
            HOST=${{ env.PROD_HOST }}
          else 
            HOST=${{ env.STAGING_HOST }}
            export DEVICE=cpu # stage server runs on cpu
          fi
          export JINA_LOG_LEVEL=DEBUG
          if [[ "${{ github.event.inputs.project }}" == "JINA" ]] ; then 
            python deploy.py --project ${{ github.event.inputs.project }} --host $HOST --port 8000 --index --query create --tag 2.6.4
          else
            python deploy.py --project ${{ github.event.inputs.project }} --host $HOST --port 8000 --index --query create
          fi
        env:
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          PROD_HOST: ${{ secrets.PROD_HOST }}
        working-directory: ./deployment
      - run: |
          if [[ "${{ github.event.inputs.project }}" == "JINA" ]] ; then 
            if [[ "${{ github.event.inputs.environment }}" == "prod" ]] ; then
              echo "DOCSBOT_SERVER=https://docsbot.jina.ai" >> $GITHUB_ENV
            elif [[ "${{ github.event.inputs.environment }}" == "stage" ]] ; then
              echo "DOCSBOT_SERVER=https://docsbot-stage.jina.ai" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.event.inputs.project }}" == "FINETUNER" ]] ; then
            if [[ "${{ github.event.inputs.environment }}" == "prod" ]] ; then
              echo "DOCSBOT_SERVER=https://finetuner-docsbot.jina.ai" >> $GITHUB_ENV
            elif [[ "${{ github.event.inputs.environment }}" == "stage" ]] ; then
              echo "DOCSBOT_SERVER=https://finetuner-docsbot-stage.jina.ai" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.event.inputs.project }}" == "FASTAPI" ]] ; then
            if [[ "${{ github.event.inputs.environment }}" == "stage" ]] ; then
              echo "DOCSBOT_SERVER=https://fastapi-docsbot-stage.jina.ai" >> $GITHUB_ENV
            elif [[ "${{ github.event.inputs.environment }}" == "prod" ]] ; then
              echo "DOCSBOT_SERVER=NOTSUPPORTEDYET" >> $GITHUB_ENV
            fi
          fi
      - name: Send message to Slack
        if: success()
        run: >
          curl -X POST -H 'Content-type: application/json' --data 
          '{
              "text": ":jina-robot-logo: reindexed & redeployed :memo: on ${{ env.DOCSBOT_SERVER }} :tada:"
          }' ${{ env.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NIGHTLY_TESTS_WEBHOOK }}
      
  redeploy-docs-staging:
    needs: [reindex-and-redeploy-query]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'stage' && github.event.inputs.project != 'FASTAPI' }}
    steps:
      - run: |
          if [[ ${{ github.event.inputs.project }} == 'JINA' ]] ; then 
            echo "REPOSITORY=jina-ai/jina" >> $GITHUB_ENV
          elif [[ ${{ github.event.inputs.project }} == 'FINETUNER' ]] ; then 
            echo "REPOSITORY=jina-ai/finetuner" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.REPOSITORY }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Deploy docs from ${{ github.event.inputs.project }} and use new host as backend
        run: |
          npm i -g netlify-cli
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [[ ${{ github.event.inputs.project }} == 'JINA' ]] ; then 
            export JINA_DOCSBOT_SERVER=https://docsbot-stage.jina.ai
          elif [[ ${{ github.event.inputs.project }} == 'FINETUNER' ]] ; then
            export FINETUNER_DOCSBOT_SERVER=https://finetuner-docsbot-stage.jina.ai
          fi
          git fetch origin --tags
          export NUM_RELEASES=1
          bash makedoc.sh
          LOWER_CASE_PROJECT=$(echo "${{ github.event.inputs.project }}" | tr '[:upper:]' '[:lower:]')
          echo "PROJECT=$LOWER_CASE_PROJECT" >> $GITHUB_ENV
          netlify deploy --dir=_build/dirhtml --alias=docsbot-${LOWER_CASE_PROJECT}-stage
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        working-directory: docs
        timeout-minutes: 15
