name: Docsbot Evaluate

concurrency:
  group: deployment-${{ github.event.inputs.branch }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-docs-bot branch name
        default: main
        required: false
      pr_number:
        description: Pass the pull request number that's triggering this job
        default: '0'
        required: false

jobs:
  evaluate-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-docs-bot
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
#      - name: download dpr models
#        run: |
#          set -ex
#          wget https://github.com/git-lfs/git-lfs/releases/download/v2.9.0/git-lfs-linux-amd64-v2.9.0.tar.gz
#          tar -xf git-lfs-linux-amd64-v2.9.0.tar.gz
#          chmod 775 install.sh
#          sudo ./install.sh
#          git clone https://huggingface.co/facebook/dpr-ctx_encoder-single-nq-base ~/dpr_index
#          cd ~/dpr_index
#          git lfs install
#          git lfs pull
#          cd ..
#          git clone https://huggingface.co/facebook/dpr-question_encoder-single-nq-base ~/dpr_query
#          cd ~/dpr_query
#          git lfs install
#          git lfs pull

      - name: install reqs (your branch)
        run: ./scripts/install_requirements.sh
      - name: evaluate
        run: |
          set -ex
          echo $(ls -la)
          bash scripts/prepare_repos.sh
          mkdir results
          cd src
          export DPR_MODEL_INDEX=facebook/dpr-ctx_encoder-single-nq-base
          export DPR_MODEL_QUERY=facebook/dpr-question_encoder-single-nq-base
          bash ../scripts/evaluate_all.sh your_branch
          cd ..
          git fetch --all
          branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
          git checkout main
          pip install -r deployment/requirements.txt
          pip install -r src/requirements.txt
          pip install -r tests/requirements.txt
          cd src
          bash ../scripts/evaluate_all.sh main
          cp *.json ../results
          cd ..
          git checkout $branch
          pip install -r scripts/requirements.txt
          python scripts/evaluation_data.py

      - name: Extract Evaluations
        id: get-comment-eval-body
        run: |
          set -ex          
          body=$(cat results/table.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body
      - name: Find Comment (Evaluation)
        if: ${{ github.event.inputs.pr_number != '0' }}
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/jina-docs-bot
          issue-number: ${{ github.event.inputs.pr_number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'reciprocal_rank'
      - name: Create comment (Evaluation)
        if: ${{ github.event.inputs.pr_number != '0' && steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/jina-docs-bot
          issue-number: ${{ github.event.inputs.pr_number }}
          body: ${{ steps.get-comment-eval-body.outputs.body }}
          reaction-type: "eyes"
      - name: Update comment (Evaluation)
        if: ${{ github.event.inputs.pr_number != '0' && steps.fc.outputs.comment-id != 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/jina-docs-bot
          issue-number: ${{ github.event.inputs.pr_number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.get-comment-eval-body.outputs.body }}
          reaction-type: "rocket"
          edit-mode: replace
