name: (docsqa) Reindex Wordlift


on:
  workflow_dispatch:
    inputs:
      version:
        description: Pass the version for Executor tagging
        default: v0.0.27
        required: true
      branch:
        description: Pass the docsQA branch/tag name
        default: master
        required: true


jobs:
  publish-wordlift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jina-ai/docsQA
          ref:  ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
          path: docsQA
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          pip install -r docsQA/service/daas/local/requirements.txt
          pip install -r docsQA/service/daas/batch/requirements.txt
      - name: Publish wordlift
        run: |
          cd ${GITHUB_WORKSPACE}/docsQA/service
          python -m daas.local.publish_wordlift --version_tag ${{ github.event.inputs.version }} --force_reindex
