name: Push Executors to Hubble & ECR (docsqa)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-docs-bot branch/tag name
        default: main
        required: false
        
jobs:
  deploy-batch-function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-docs-bot
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Patch & Push to Hubble & ECR
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          export PATCH_JINA_PREVIEW=true
          python hubblepush.py
        working-directory: ./deployment2/local
          
