name: (docsqa) Serverless deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-docs-bot branch/tag name
        default: docsqa-as-a-service
        required: false
        
jobs:
  serverless-deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-docs-bot
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
      - name: Install Node.js
        uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Serverless & Deploy App
        run: |
          npm install serverless serverless-python-requirements serverless-domain-manager
          python -m pip install --upgrade pip
          pip install -r serverless-requirements.txt
          bash serverless-deploy.sh node_modules/serverless/bin/serverless.js
        env:
          JINA_CLOUDFLARE_ZONE: ${{ secrets.JINA_CLOUDFLARE_ZONE }}
          JINA_CLOUDFLARE_TOKEN: ${{ secrets.JINA_CLOUDFLARE_TOKEN }}
          DOCSQA_ATLAS_HOSTNAME: ${{ secrets.DOCSQA_ATLAS_HOSTNAME }}
          DOCSQA_ATLAS_DATABASE: ${{ secrets.DOCSQA_ATLAS_DATABASE }}
          DOCSQA_ATLAS_PROJECTS: ${{ secrets.DOCSQA_ATLAS_PROJECTS }}
          DOCSQA_ATLAS_METADATA: ${{ secrets.DOCSQA_ATLAS_METADATA }}
          DOCSQA_ATLAS_USERNAME: ${{ secrets.DOCSQA_ATLAS_USERNAME }}
          DOCSQA_ATLAS_PASSWORD: ${{ secrets.DOCSQA_ATLAS_PASSWORD }}
          DOCSQA_BATCH_JOB_QUEUE: ${{ secrets.DOCSQA_BATCH_JOB_QUEUE }}
          DOCSQA_BATCH_JOB_DEFINITION: ${{ secrets.DOCSQA_BATCH_JOB_DEFINITION }}
        working-directory: ./deployment2/cloud
     
