name: (docsqa) Update all projects

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the docsQA branch/tag name
        default: master
        required: false
    schedule:
      - cron: "0 2 * * 1" # runs at 02:00 every Monday
        
jobs:
  update-all-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/docsQA
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Pip Install and JCloud Auth Setup
        run: |
          python -m pip install --upgrade pip
          export JINA_VERSION=`cat jina_version.txt`
          pip install -r service/daas/local/requirements.txt
          pip install -r service/daas/batch/requirements.txt
          mkdir -p ~/.jina
          echo "{\"auth_token\": \"${DOCSQA_WOLF_TOKEN}\"}" > ~/.jina/config.json
        env:
          DOCSQA_WOLF_TOKEN: ${{ secrets.DOCSQA_WOLF_TOKEN }}
      - name: Update all projects
        run: |
          python -m daas.local.update_projects --project all
        env:
          DOCSQA_ATLAS_HOSTNAME: ${{ secrets.DOCSQA_ATLAS_HOSTNAME }}
          DOCSQA_ATLAS_DATABASE: ${{ secrets.DOCSQA_ATLAS_DATABASE }}
          DOCSQA_ATLAS_PROJECTS: ${{ secrets.DOCSQA_ATLAS_PROJECTS }}
          DOCSQA_ATLAS_METADATA: ${{ secrets.DOCSQA_ATLAS_METADATA }}
          DOCSQA_ATLAS_VERSIONS: ${{ secrets.DOCSQA_ATLAS_VERSIONS }}
          DOCSQA_ATLAS_USERNAME: ${{ secrets.DOCSQA_ATLAS_USERNAME }}
          DOCSQA_ATLAS_PASSWORD: ${{ secrets.DOCSQA_ATLAS_PASSWORD }}
          DOCSQA_ATLAS_FEEDBACKS: ${{ secrets.DOCSQA_ATLAS_FEEDBACKS }}
          DOCSQA_ATLAS_QUERIES: ${{ secrets.DOCSQA_ATLAS_QUERIES }}
          DOCSQA_JINA_DEV_BOT: ${{ secrets.JINA_DEV_BOT }}
        working-directory: ./service
