name: (jcloud) Notify Current Flows on Slack

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-operator branch
        required: true
        default: main
      channel:
        description: Pass the slack channel ID to send notifications to
        required: true
        default: C04SZ7AAWQZ
  schedule:
    - cron: "30 0 * * 1-5"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup docsqa-cluster & port-forward Thanos
        run: |
          aws eks update-kubeconfig --region us-east-1 --name docsqa-cluster
          kubectl port-forward service/thanos-query -n monitor 9090:9090
      - uses: actions/checkout@v3
        with:
          repository: jina-ai/jina-operator
          ref: ${{ github.events.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./scripts/
      - name: Notify on Slack
        run: python notify.py
        working-directory: ./scripts/
        env:
          SLACK_TOKEN: ${{ secrets.FLOWS_NOTIFIER_SLACK_TOKEN }}
          JCLOUD_M2M_TOKEN: ${{ secrets.JCLOUD_M2M_TOKEN }}
          MONGO_URI: ${{ secrets.PROD_MONGO_URI }}
          SLACK_CHANNEL_ID: ${{ github.event.inputs.channel == '' && 'C04SZ7AAWQZ' || github.event.inputs.channel }}
