name: (jc-operator) Integration Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-operator branch
        required: false
        default: main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-operator
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.JINA_DEV_BOT }}
      
      - name: Set up Golang 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          go mod tidy -v
          go install github.com/onsi/ginkgo/ginkgo@v1.16.5
          go get github.com/onsi/gomega/...
          python -m pip install --upgrade pip
          pip install "jina[standard]"
        working-directory: ./operator

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.JC_CI_AWS_REGION }}

      - name: Update Cluster Config
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.K8S_CLUSTER }}
        env:
          AWS_REGION: ${{ secrets.JC_CI_AWS_REGION }}
          K8S_CLUSTER: ${{ secrets.JC_CI_K8S_CLUSTER }}
      
      - name: Run E2E Integration Test Suites
        run: make integration-tests
        env:
          USE_EXISTING_CLUSTER: true
          ACK_GINKGO_RC: true
          ACK_GINKGO_DEPRECATIONS: 1.16.5
        working-directory: ./operator
