name: (jc-operator) DEBUG WILL REMOVE LATER

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-operator branch
        required: true
      only_api_changed:
        description: Set to true to if only API code was changed
        type: boolean
        default: false
        required: false

jobs:
  compatibility-test:
    if: ${{ inputs.only_api_changed != 'true'}}
    steps: 
      - name: "TEST
        run: |
          echo "AAJAJAJAJAJJA"

  # compatibility-test:
  #   if: ${{ (github.event.inputs.branch != 'main') && (github.event.inputs.only_api_changed == 'false') }}
  #   uses: jina-ai/cloud-ops/.github/workflows/operator-backward-compatibility-tests.yml@master
  #   secrets: inherit
  #   with:
  #     branch: ${{ github.event.inputs.branch }}

  success-all-test:
    needs: 
      - compatibility-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "All Done"
