name: (jc-operator) Compatibility Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-operator branch
        required: true
      manual_run:
        default: false
        required: false
        type: boolean
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      manual_run:
        description: Please check if this job is manually run.
        default: true
        required: false
        type: boolean

concurrency:
  group: operator-compatibility-tests
  cancel-in-progress: false

jobs:
  build-operator-from-branch:
    # Build only when it's triggered directly; the image has been built if this is triggered from integration tests.
    if: ${{ github.event.inputs.manual_run != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: | 
          echo '${{github.event.inputs.manual_run}}'
          echo '${{inputs.manual_run}}'
          echo '${{github.event_name}}'

  success-all-test:
    needs: 
      - build-operator-from-branch
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "All Done"
