name: Validate concurrency

on:
  workflow_dispatch:
    inputs:
      project:
        description: Pass the project name (JINA/FINETUNER)
        default: JINA
        required: false
      environment:
        description: Pass the environment (prod/stage)
        default: stage
        required: false

concurrency: deployment-${{ github.event.inputs.environment }}-${{ github.event.inputs.project }}

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi"
      
  stage:
    needs: [first]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'stage' }}
    steps:
      - run: |
          echo "Hi stage ${{ github.event.inputs.environment }}"
          sleep 5
          LOWER_CASE_PROJECT=$(echo "${{ github.event.inputs.project }}" | tr '[:upper:]' '[:lower:]')
          echo "PROJECT=$LOWER_CASE_PROJECT" >> $GITHUB_ENV
          echo $LOWER_CASE_PROJECT

  prod:
    needs: [first]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}
    steps:
      - run: |
          echo "Hi prod ${{ github.event.inputs.environment }}"
          sleep 10
