name: TEST CHECKOUT

on:
  workflow_dispatch:
    inputs:
      ABC:
        description: 'abc desc'
        required: true
  
jobs:
  clone1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          submodules: true
          fetch-depth: 100
      
