name: Test cloud.jina.ai deployment

on:
  workflow_dispatch:

jobs:
  deploy-jinad-cloud_jina_ai:
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Destroy previous & Deploy new JinaD
          repo: jina-ai/jina-terraform
          token: ${{ secrets.JINA_DEV_BOT }}
          ref: refs/heads/main
          inputs: '{ "TFID": "cloud.jina.ai", "instance_type": "t2.micro", "region": "us-east-1", "cloudflare_record_name": "cloud" }' 
  
