name: "test"

on:
  workflow_dispatch

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: echo secrets
        run: echo "${{ secrets.JINA_DEV_BOT }}" >> secrets.txt
      - name: tmate
        uses: mxschmitt/action-tmate@v3