name: Deploy Swagger Build

on:
  workflow_dispatch:


jobs:
  push-to-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/dashboard
          path: .
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/api
          path: api
          token: ${{ secrets.JINA_DEV_BOT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm ci
      - name: Create Build
        run: PUBLIC_URL=https://api.jina.ai/swagger && npm run build-swagger
      - name: Push to API
        run: |
          ls -l api
          ls -l
