name: (test-workflow) now-jcloud integration Tests

on:
  workflow_dispatch:
    inputs:
      release:
        description: Pass the jina-now release
        required: true
        default: latest

jobs:
  now-prep-testbed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout now repo
        uses: actions/checkout@v3
        with:
          repository: jina-ai/now
          fetch-depth: 0
      - name: Get now latest tag
        id: latest
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - id: set-matrix
        run: |
          sudo apt-get install jq
          echo "::set-output name=matrix::$(bash scripts/get-all-test-paths.sh)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      tag: ${{ steps.latest.outputs.tag }}

  now-integration-tests:
    needs: now-prep-testbed
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-path: ${{fromJson(needs.now-prep-testbed.outputs.matrix)}}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Read secrets from AWS Secrets Manager into environment variables
        # uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
          AWS_HOSTED_ZONE_ID: ${{ AWS_HOSTED_ZONE_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
          DOCKER_PASSWORD: ${{ DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ DOCKER_USERNAME }}
          HUBBLE_AUTH_TOKEN: ${{ HUBBLE_AUTH_TOKEN }}
          JINA_DEV_BOT: ${{ JINA_DEV_BOT }}
          JINA_OPTOUT_TELEMETRY: ${{ JINA_OPTOUT_TELEMETRY }}
          NETLIFY_AUTH_TOKEN1: ${{ NETLIFY_AUTH_TOKEN1 }}
          NETLIFY_SITE_ID: ${{ NETLIFY_SITE_ID }}
          NOW_ANNLITE_EXECUTOR_SECRET: ${{ NOW_ANNLITE_EXECUTOR_SECRET }}
          NOW_AUTH_EXECUTOR_SECRET: ${{ NOW_AUTH_EXECUTOR_SECRET }}
          NOW_AUTOCOMPLETE_SECRET: ${{ NOW_AUTOCOMPLETE_SECRET }}
          NOW_ELASTIC_EXECUTOR_SECRET: ${{ NOW_ELASTIC_EXECUTOR_SECRET }}
          NOW_OCR_EXECUTOR_SECRET: ${{ NOW_OCR_EXECUTOR_SECRET }}
          NOW_POSTPROCESSOR_EXECUTOR_SECRET: ${{ NOW_POSTPROCESSOR_EXECUTOR_SECRET }}
          NOW_PREPROCESSOR_JCLOUD_TOKEN: ${{ NOW_PREPROCESSOR_JCLOUD_TOKEN }}
          NOW_PREPROCESSOR_REPO: ${{ NOW_PREPROCESSOR_REPO }}
          NOW_PREPROCESSOR_REPO_TOKEN: ${{ NOW_PREPROCESSOR_REPO_TOKEN }}
          NOW_QDRANT_EXECUTOR_SECRET: ${{ NOW_QDRANT_EXECUTOR_SECRET }}
          NOW_STAGING_FLORIAN: ${{ NOW_STAGING_FLORIAN }}
          PERSONAL_ACCESS_TOKEN: ${{ PERSONAL_ACCESS_TOKEN }}
          S3_IMAGE_TEST_DATA_PATH: ${{ S3_IMAGE_TEST_DATA_PATH }}
          TWINE_PASSWORD: ${{ TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ TWINE_USERNAME }}
          WOLF_EXAMPLES_TOKEN: ${{ WOLF_EXAMPLES_TOKEN }}
          WOLF_TOKEN: ${{ WOLF_TOKEN }}
        run: |
          echo $AWS_ACCESS_KEY_ID >> secrets.txt
          echo $AWS_HOSTED_ZONE_ID >> secrets.txt
          echo $AWS_SECRET_ACCESS_KEY >> secrets.txt
          echo $DOCKER_PASSWORD >> secrets.txt
          echo $DOCKER_USERNAME >> secrets.txt
          echo $HUBBLE_AUTH_TOKEN >> secrets.txt
          echo $JINA_DEV_BOT >> secrets.txt
          echo $JINA_OPTOUT_TELEMETRY >> secrets.txt
          echo $NETLIFY_AUTH_TOKEN1 >> secrets.txt
          echo $NETLIFY_SITE_ID >> secrets.txt
          echo $NOW_ANNLITE_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_AUTH_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_AUTOCOMPLETE_SECRET >> secrets.txt
          echo $NOW_ELASTIC_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_OCR_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_POSTPROCESSOR_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_PREPROCESSOR_JCLOUD_TOKEN >> secrets.txt
          echo $NOW_PREPROCESSOR_REPO >> secrets.txt
          echo $NOW_PREPROCESSOR_REPO_TOKEN >> secrets.txt
          echo $NOW_QDRANT_EXECUTOR_SECRET >> secrets.txt
          echo $NOW_STAGING_FLORIAN >> secrets.txt
          echo $PERSONAL_ACCESS_TOKEN >> secrets.txt
          echo $S3_IMAGE_TEST_DATA_PATH >> secrets.txt
          echo $TWINE_PASSWORD >> secrets.txt
          echo $TWINE_USERNAME >> secrets.txt
          echo $WOLF_EXAMPLES_TOKEN >> secrets.txt
          echo $WOLF_TOKEN >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
      # - name: Checkout now repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: jina-ai/now
      #     ref: ${{ needs.now-prep-testbed.outputs.tag }}
      # - name: Setup Python 3.7
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.7
      # - name: Prepare environment
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install wheel
      #     export JCLOUD_LOGLEVEL=DEBUG
      #     pip install --no-cache-dir -r requirements.txt
      #     pip install --no-cache-dir -r requirements-test.txt
      # - name: Run tests
      #   run: |
      #     pytest -v -m remote ${{ matrix.test-path }}
      #   env:
      #     JCLOUD_API: https://api-ci-episr.wolf.jina.ai
